export const TOPICS = [
  `Criminal Justice`,
  `Development`,
  `Education`,
  `Elections`,
  `Environment`,
  `Finance`,
  `Health`,
  `Housing`,
  `Labor`,
  `Libraries`,
  `Parks`,
  `Politics`,
  `Transportation`,
  `Urban Animals`,
  `Utilities`,
]

export const TOPIC_COLOR_MAP = {
  "Criminal Justice": `blue`,
  Development: `brown`,
  Education: `red`,
  Elections: `red`,
  Environment: `green`,
  Finance: `yellow`,
  Health: `green`,
  Housing: `brown`,
  Labor: `yellow`,
  Libraries: `red`,
  Parks: `green`,
  Politics: `red`,
  Transportation: `brown`,
  "Urban Animals": `blue`,
  Utilities: `blue`,
}
